import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getUserInfo } from "./lib/action";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userInfoResponse = await getUserInfo();
  return (
    <html lang="en">
      <body className={inter.className}>
        {userInfoResponse.code === 200 && (
          <div>{JSON.stringify(userInfoResponse.data)}</div>
        )}
        {children}
      </body>
    </html>
  );
}
